In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.5.3


In [11]:
data_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(data_list)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [12]:
array_1d = np.array(data_list)
print(array_1d)
print(type(array_1d))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


In [15]:
print(array_1d.ndim)
print(array_1d.shape)
print(array_1d.size)
print(array_1d.dtype)

1
(10,)
10
int64


In [16]:
data_2d_list = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 0],
    [10, 11, 12, 13, 14],
]
print(data_2d_list)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0], [10, 11, 12, 13, 14]]


In [17]:
array_2d = np.array(data_2d_list)
print(array_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [10 11 12 13 14]]


In [18]:
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d.size)
print(array_2d.dtype)

2
(3, 5)
15
int64


In [19]:
print(data_list * 2)
print(array_1d * 2)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[ 20  40  60  80 100 120 140 160 180 200]


In [24]:
# Фабрика массивов
zerros_array = np.zeros(10)
print(zerros_array)
print(zerros_array.dtype)

ones_array = np.ones(7)
print(ones_array)
print(ones_array.dtype)

empty_array = np.empty(5)
print(empty_array)
print(empty_array.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[1. 1. 1. 1. 1. 1. 1.]
float64
[4.94e-323 9.88e-323 1.48e-322 1.98e-322 2.47e-322]
float64


In [26]:
time_sec = np.arange(0, 61, 10)
print(time_sec)
print(time_sec.size)

[ 0 10 20 30 40 50 60]
7


In [28]:
time_sec = np.linspace(1, 60, 10)
print(time_sec)
print(time_sec.size)

[ 1.          7.55555556 14.11111111 20.66666667 27.22222222 33.77777778
 40.33333333 46.88888889 53.44444444 60.        ]
10


In [29]:
mix_array = np.array([1, 2, 3.5, 7, 9, 11.12])
print(mix_array)
print((mix_array.dtype))

[ 1.    2.    3.5   7.    9.   11.12]
float64


In [30]:
mix_array = np.array(['1', 2, 3.5, '7', 9, '11.12'])
print(mix_array)
print((mix_array.dtype))

['1' '2' '3.5' '7' '9' '11.12']
<U32


In [33]:

ones_array = np.ones(5, dtype=np.int64)
print(ones_array)
print(ones_array.dtype)

empty_array = np.empty(5, dtype=np.int16)
print(empty_array)
print(empty_array.dtype)

print(ones_array.itemsize)
print(empty_array.itemsize)

print(ones_array.nbytes)
print(empty_array.nbytes)

[1 1 1 1 1]
int64
[257 257 257 257 257]
int16
8
2
40
10


In [34]:
# Формы массива

In [36]:
temp_list = [
    18.2, 18.9, 19.4,
    18.0, 18.7, 19.1,
    17.7, 18.6, 19.0,
    18.1, 18.9, 19.4,
    18.2, 18.2, 19.8,
    13.4, 18.9, 16.4,
    19.2, 14.1, 15.4,
    12.6, 16.9, 14.9,
    17.8, 13.1, 19.6,
    14.4, 18.2, 18.7,
    12.2, 12.6, 14.2,
    13.5, 17.1, 16.3,
    14.1, 12.5, 12.4,
    18.2, 14.7, 11.4,

]
print(temp_list)

[18.2, 18.9, 19.4, 18.0, 18.7, 19.1, 17.7, 18.6, 19.0, 18.1, 18.9, 19.4, 18.2, 18.2, 19.8, 13.4, 18.9, 16.4, 19.2, 14.1, 15.4, 12.6, 16.9, 14.9, 17.8, 13.1, 19.6, 14.4, 18.2, 18.7, 12.2, 12.6, 14.2, 13.5, 17.1, 16.3, 14.1, 12.5, 12.4, 18.2, 14.7, 11.4]


In [40]:
temp_values = np.array(temp_list)
print(temp_values)
print(temp_values.ndim)
print(temp_values.shape)
print(temp_values.size)

[18.2 18.9 19.4 18.  18.7 19.1 17.7 18.6 19.  18.1 18.9 19.4 18.2 18.2
 19.8 13.4 18.9 16.4 19.2 14.1 15.4 12.6 16.9 14.9 17.8 13.1 19.6 14.4
 18.2 18.7 12.2 12.6 14.2 13.5 17.1 16.3 14.1 12.5 12.4 18.2 14.7 11.4]
1
(42,)
42


In [41]:
temp_days = temp_values.reshape(14, 3)
print(temp_days)
print(temp_days.ndim)
print(temp_days.shape)
print(temp_days.size)

[[18.2 18.9 19.4]
 [18.  18.7 19.1]
 [17.7 18.6 19. ]
 [18.1 18.9 19.4]
 [18.2 18.2 19.8]
 [13.4 18.9 16.4]
 [19.2 14.1 15.4]
 [12.6 16.9 14.9]
 [17.8 13.1 19.6]
 [14.4 18.2 18.7]
 [12.2 12.6 14.2]
 [13.5 17.1 16.3]
 [14.1 12.5 12.4]
 [18.2 14.7 11.4]]
2
(14, 3)
42


In [42]:
temp_days_1 = temp_values.reshape(-1, 3)
print(temp_days_1)
print(temp_days_1.ndim)
print(temp_days_1.shape)
print(temp_days_1.size)

[[18.2 18.9 19.4]
 [18.  18.7 19.1]
 [17.7 18.6 19. ]
 [18.1 18.9 19.4]
 [18.2 18.2 19.8]
 [13.4 18.9 16.4]
 [19.2 14.1 15.4]
 [12.6 16.9 14.9]
 [17.8 13.1 19.6]
 [14.4 18.2 18.7]
 [12.2 12.6 14.2]
 [13.5 17.1 16.3]
 [14.1 12.5 12.4]
 [18.2 14.7 11.4]]
2
(14, 3)
42


In [43]:
temp_days_3d = temp_values.reshape(2, 7, 3)
print(temp_days_3d)
print(temp_days_3d.ndim)
print(temp_days_3d.shape)
print(temp_days_3d.size)

[[[18.2 18.9 19.4]
  [18.  18.7 19.1]
  [17.7 18.6 19. ]
  [18.1 18.9 19.4]
  [18.2 18.2 19.8]
  [13.4 18.9 16.4]
  [19.2 14.1 15.4]]

 [[12.6 16.9 14.9]
  [17.8 13.1 19.6]
  [14.4 18.2 18.7]
  [12.2 12.6 14.2]
  [13.5 17.1 16.3]
  [14.1 12.5 12.4]
  [18.2 14.7 11.4]]]
3
(2, 7, 3)
42


In [45]:
#resize

base_array = np.array([10, 20, 30, 40, 50, 60])
print(base_array)

[10 20 30 40 50 60]


In [46]:
resh_array = base_array.reshape(2, 3)
print(resh_array)
print(resh_array.ndim)
print(resh_array.shape)
print(resh_array.size)

[[10 20 30]
 [40 50 60]]
2
(2, 3)
6


In [56]:
resize_array =  np.resize(base_array, 7)
print(resize_array)
print(resize_array.ndim)
print(resize_array.shape)
print(resize_array.size)

[10 20 30 40 50 60 10]
1
(7,)
7


In [58]:
resh_array = resize_array.reshape(4, 3)
print(resh_array)
print(resh_array.ndim)
print(resh_array.shape)
print(resh_array.size)

ValueError: cannot reshape array of size 7 into shape (4,3)

In [66]:
# Индексы и срезы
temp_values = np.array(temp_list)
print(temp_values)

print(temp_values[0])
print(temp_values[3])
print(temp_values[-2])
print(len(temp_values))

print(temp_values[0:3])
print(temp_values[::3])
print(temp_values[::-1])

[18.2 18.9 19.4 18.  18.7 19.1 17.7 18.6 19.  18.1 18.9 19.4 18.2 18.2
 19.8 13.4 18.9 16.4 19.2 14.1 15.4 12.6 16.9 14.9 17.8 13.1 19.6 14.4
 18.2 18.7 12.2 12.6 14.2 13.5 17.1 16.3 14.1 12.5 12.4 18.2 14.7 11.4]
18.2
18.0
14.7
42
[18.2 18.9 19.4]
[18.2 18.  17.7 18.1 18.2 13.4 19.2 12.6 17.8 14.4 12.2 13.5 14.1 18.2]
[11.4 14.7 18.2 12.4 12.5 14.1 16.3 17.1 13.5 14.2 12.6 12.2 18.7 18.2
 14.4 19.6 13.1 17.8 14.9 16.9 12.6 15.4 14.1 19.2 16.4 18.9 13.4 19.8
 18.2 18.2 19.4 18.9 18.1 19.  18.6 17.7 19.1 18.7 18.  19.4 18.9 18.2]


In [60]:
temp_days = temp_values.reshape(14, 3)
print(temp_days)

[[18.2 18.9 19.4]
 [18.  18.7 19.1]
 [17.7 18.6 19. ]
 [18.1 18.9 19.4]
 [18.2 18.2 19.8]
 [13.4 18.9 16.4]
 [19.2 14.1 15.4]
 [12.6 16.9 14.9]
 [17.8 13.1 19.6]
 [14.4 18.2 18.7]
 [12.2 12.6 14.2]
 [13.5 17.1 16.3]
 [14.1 12.5 12.4]
 [18.2 14.7 11.4]]


In [67]:
print(temp_days[0])
print(temp_days[3])
print(temp_days[-2])

[18.2 18.9 19.4]
[18.1 18.9 19.4]
[14.1 12.5 12.4]


In [68]:
print(temp_days[0][1])
print(temp_days[3][0])
print(temp_days[-2][-1])

18.9
18.1
12.4


In [69]:
print(temp_days[0, 1])
print(temp_days[3, 0])
print(temp_days[-2, -1])

18.9
18.1
12.4


In [70]:
print(temp_days[0:5, 0:2])
print(temp_days[:, 1])


[[18.2 18.9]
 [18.  18.7]
 [17.7 18.6]
 [18.1 18.9]
 [18.2 18.2]]
[18.9 18.7 18.6 18.9 18.2 18.9 14.1 16.9 13.1 18.2 12.6 17.1 12.5 14.7]


In [72]:
data = np.array([
    [12, 3, 5, 7, 14],
    [11, 15, 9, 6, 20],
    [2, 13, 10, 0, 1],
])
print(data)

[[12  3  5  7 14]
 [11 15  9  6 20]
 [ 2 13 10  0  1]]


In [73]:
data[1, 2] = 99
print(data)

[[12  3  5  7 14]
 [11 15 99  6 20]
 [ 2 13 10  0  1]]


In [74]:
data += 10
print(data)

[[ 22  13  15  17  24]
 [ 21  25 109  16  30]
 [ 12  23  20  10  11]]


In [75]:
data_1 = data - 100
print(data_1)

[[-78 -87 -85 -83 -76]
 [-79 -75   9 -84 -70]
 [-88 -77 -80 -90 -89]]


In [76]:
win_view = data[0:2, 1:4]
print(win_view)

[[ 13  15  17]
 [ 25 109  16]]


In [77]:
win_view[0, 0] = 777
print(win_view)

[[777  15  17]
 [ 25 109  16]]


In [79]:
print(data)

[[ 22 777  15  17  24]
 [ 21  25 109  16  30]
 [ 12  23  20  10  11]]


In [80]:
win_view_new = data[0:2, 1:4].copy()
print(win_view_new)

[[777  15  17]
 [ 25 109  16]]


In [81]:
win_view_new[0, 0] = 555
print(win_view_new)

[[555  15  17]
 [ 25 109  16]]


In [82]:
print(data)

[[ 22 777  15  17  24]
 [ 21  25 109  16  30]
 [ 12  23  20  10  11]]


In [83]:
data_1 = np.array([1, 2, 3, 4, 5])
data_2 = np.array([11, 22, 33, 44, 55])

In [84]:
print(data_1)
print(data_2)

[1 2 3 4 5]
[11 22 33 44 55]


In [86]:
result = data_1 + data_2
print(result)
res = result * 3
print(res)

[12 24 36 48 60]
[ 36  72 108 144 180]


In [87]:
data_3 = np.array([111, 22, 5433, 1, 55])
print(data_3)

[ 111   22 5433    1   55]


In [90]:
print(data_3.max())
print(data_3.min())
print(data_3.sum())



5433
1
5622


In [91]:
print(temp_days.max())
print(temp_days.min())
print(temp_days.sum())


19.8
11.4
693.0


In [92]:
print(data.max(axis=1))
print(temp_days.min(axis=0))
print(temp_days.sum(axis=1))

[777 109  23]
[12.2 12.5 11.4]
[56.5 55.8 55.3 56.4 56.2 48.7 48.7 44.4 50.5 51.3 39.  46.9 39.  44.3]
